# Generated by Django 5.2.1 on 2025-05-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Livro: ')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor: ')),
                ('editora', models.CharField(max_length=100, verbose_name='Editora: ')),
            ],
        ),
    ]
