# Generated by Django 5.2.1 on 2025-05-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ano de Publicação'),
        ),
        migrations.AddField(
            model_name='livro',
            name='anotacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações'),
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='livro',
            name='npaginas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='N° de Páginas'),
        ),
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='livro',
            name='tradudor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tradutor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(max_length=100, verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
