# Generated by Django 5.2.1 on 2025-05-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_livro_ano_livro_anotacoes_livro_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[('Lido', 'Lido'), ('Não lido', 'Não lido')], default='Não lido', max_length=20, verbose_name='Status'),
        ),
    ]
