# Generated by Django 5.2.1 on 2025-05-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_alter_livro_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Minha Biblioteca', max_length=100)),
            ],
        ),
    ]
