# Generated by Django 5.2.1 on 2025-05-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_libconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibConfig',
            new_name='BTitulo',
        ),
        migrations.RenameField(
            model_name='btitulo',
            old_name='title',
            new_name='titulo',
        ),
    ]
