# Generated by Django 5.2.1 on 2025-05-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_rename_libconfig_btitulo_rename_title_btitulo_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BTitulo',
        ),
    ]
