# Generated by Django 5.2.1 on 2025-05-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0008_delete_btitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
