# Generated by Django 5.2.1 on 2025-05-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
