# Generated by Django 5.2.1 on 2025-05-29 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0010_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='Ano de Publicação'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Digite apenas letras (sem números ou símbolos).', regex='^[^\\W\\d_]+(?:\\s[^\\W\\d_]+)*$')], verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Digite apenas letras (sem números ou símbolos).', regex='^[^\\W\\d_]+(?:\\s[^\\W\\d_]+)*$')], verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='npaginas',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='N° de Páginas'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='tradutor',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Digite apenas letras (sem números ou símbolos).', regex='^[^\\W\\d_]+(?:\\s[^\\W\\d_]+)*$')], verbose_name='Tradutor'),
        ),
    ]
