# Generated by Django 5.2.1 on 2025-05-29 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0011_alter_livro_ano_alter_livro_autor_alter_livro_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[^\\W\\d_]+(?:\\s[^\\W\\d_]+)*$')], verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[^\\W\\d_]+(?:\\s[^\\W\\d_]+)*$')], verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='tradutor',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[^\\W\\d_]+(?:\\s[^\\W\\d_]+)*$')], verbose_name='Tradutor'),
        ),
    ]
