# Generated by Django 5.2.1 on 2025-06-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0012_alter_livro_autor_alter_livro_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='anotacoes',
            field=models.FileField(blank=True, null=True, upload_to='anotacoes/'),
        ),
    ]
