# Generated by Django 5.2.1 on 2025-06-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0013_alter_livro_anotacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='arquivo_anotacoes',
            field=models.FileField(blank=True, null=True, upload_to='anotacoes/'),
        ),
    ]
