# Generated by Django 5.2.1 on 2025-06-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0014_livro_arquivo_anotacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='arquivo_anotacoes',
        ),
        migrations.AlterField(
            model_name='livro',
            name='anotacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações'),
        ),
    ]
