# Generated by Django 5.2.1 on 2025-06-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0016_livro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Preço'),
        ),
    ]
