# Generated by Django 5.2.1 on 2025-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0018_biblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição da Biblioteca'),
        ),
    ]
