# Generated by Django 5.2.1 on 2025-06-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0019_biblioteca_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='descricao',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Descrição da Biblioteca'),
        ),
    ]
